# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'sqlite' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for sqlite
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'React', :path => '../node_modules/react-native'
  pod 'react-native-sqlite-storage', :path => '../node_modules/react-native-sqlite-storage'

  target 'sqlite-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'sqliteTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
